_target_: lightning.Trainer
default_root_dir: ${paths.run_dir}
max_epochs: 50
max_steps: -1
accelerator: gpu
devices: 2
strategy: ddp_find_unused_parameters_true
precision: 16-mixed
accumulate_grad_batches: 2
gradient_clip_val: 1.0
log_every_n_steps: 10
enable_checkpointing: true
enable_model_summary: true
num_sanity_val_steps: 0
detect_anomaly: false
check_val_every_n_epoch: 1
