wandb:
  _target_: lightning.pytorch.loggers.wandb.WandbLogger
  project: sepfp
  name: sepfp-asid-only-clo81l4k-epoch109
  save_dir: ${paths.wandb_dir}
  offline: false
  log_model: false
  save_code: true
  group: asid-only-finetune
  tags:
    - asid-only
    - finetune
    - evidence-projector
    - encoder-frozen
    - decoder-frozen
    - resume-weights-only
    - compression-aug
    - clo81l4k
  job_type: finetune
  prefix: ""
