run_group: ${task_name}
run_id: ${now:%Y-%m-%d_%H-%M-%S}
run_dir: ${hydra:runtime.cwd}/runs/${paths.run_group}/${paths.run_id}

checkpoint_dir: ${paths.run_dir}/checkpoints
wandb_dir: ${paths.run_dir}
csv_dir: ${paths.run_dir}/logs
probe_dirname: probe_eval
