defaults:
  - data: full
  - model: sepfp_route_evidence
  - loss: sepfp
  - optimizer: default
  - scheduler: null
  - trainer: full_route_evidence
  - callbacks: full
  - logger: wandb
  - _self_

task_name: train_sepfp
seed: 0
